apiVersion: v1
kind: Service
metadata:
  name: datasync
  namespace: datasync
  labels:
    name: datasync
spec:
  type: ClusterIP
  ports:
    - targetPort: 5001
      port: 5001
  selector:
    name: datasync
