version: '3.9'

services:
  frontend:
    container_name: frontend
    env_file: 
      - ./src/frontend/.env
    restart: always
    build: ./src/frontend
    command: app.js

  backend:
    container_name: backend
    env_file: 
      - ./src/backend/backend.env
    restart: always
    build: ./src/backend
    ports:
      - "5000:5000"
    volumes:
      - ./src/backend:/home/app/
    command: setup.py -s backend
    depends_on:
      - redis-primary
      - redis-secondary
      - datasync
      - frontend
  
  datasync:
    container_name: datasync
    env_file: 
      - ./src/backend/backend.env
    restart: always
    build: ./src/backend
    ports:
      - "5001:5001"
    volumes:
      - ./src/backend:/home/app/
    command: setup.py -s sync
    depends_on:
      - redis-primary
      - redis-secondary

  redis-primary:
    image: docker.io/bitnami/redis:6.2
    ports:
      - '6379'
    env_file: 
      - ./src/backend/redis_primary.env
    volumes:
      - 'redis_data:/bitnami/redis/data'

  redis-secondary:
    image: docker.io/bitnami/redis:6.2
    ports:
      - '6379'
    depends_on:
      - redis-primary
    env_file: 
      - ./src/backend/redis_secondary.env

volumes:
  redis_data:
    driver: local
