version: '3.9'

services:
  # How to setup Traefik
  # https://www.youtube.com/watch?v=7N5O62FjGDc
  reverse-proxy:
    container_name: traefik-reverse-proxy
    image: traefik:v2.8
    env_file: 
      - ./src/traefik/traefik.env
    command: 
      - --api=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
    ports:
      # The HTTP port
      - "80:80"
      - "8080:8080"
      - "443:443"
    restart: always
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-public-certificates:/certificates
    labels:
      - traefik.http.services.app.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-dashboard.entrypoints=http
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.feyre.io`)
      - traefik.http.routers.traefik-dashboard.entrypoints=https
      - traefik.http.routers.traefik-dashboard.tls=true
      - traefik.http.routers.traefik-dashboard.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-dashboard.middlewares=https-redirect
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME}:${HASHED_PASSWORD}
      - traefik.http.routers.traefik-dashboard.middlewares=admin-auth

  # Frontend service
  frontend:
    container_name: frontend
    env_file: 
      - ./src/frontend/frontend.env
    restart: unless-stopped
    build: ./src/frontend
    command: index.js
    volumes:
      - log-volume:/home/app/logs

  # Backend Service
  backend:
    container_name: backend
    env_file: 
      - ./src/backend/backend.env
    restart: unless-stopped
    build: ./src/backend
    ports:
      - "5000:5000"
    volumes:
      - log-volume:/home/app/logs
    command: setup.py -s backend
    depends_on:
      - redis-primary
      - redis-secondary
      - datasync
      - frontend
  
  # Data sync service
  datasync:
    container_name: datasync
    env_file: 
      - ./src/backend/backend.env
    restart: unless-stopped
    build: ./src/backend
    ports:
      - "5001:5001"
    volumes:
      - log-volume:/home/app/logs
    command: setup.py -s sync
    depends_on:
      - redis-primary
      - redis-secondary

  # Public Stats Service
  public:
    container_name: public
    env_file: 
      - ./src/backend/backend.env
    restart: unless-stopped
    build: ./src/backend
    ports:
      - "5002:5002"
    expose:
      - 5002
    volumes:
      - log-volume:/home/app/logs
    command: setup.py -s public
    depends_on:
      - redis-primary
      - redis-secondary
      - datasync
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=5002
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`api.feyre.io`)
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.rule=Host(`api.feyre.io`)
      - traefik.http.routers.app-https.tls=true
      - traefik.http.routers.app-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.app-http.middlewares=https-redirect
    networks:
      - traefik-public

  # Primary redis
  redis-primary:
    container_name: redis-primary
    image: docker.io/bitnami/redis:6.2
    restart: unless-stopped
    ports:
      - '6379'
    env_file: 
      - ./src/backend/redis-primary.env
    volumes:
      - 'redis_data:/bitnami/redis/data'

  # Secondary Redis
  redis-secondary:
    container_name: redis-secondary
    image: docker.io/bitnami/redis:6.2
    restart: unless-stopped
    ports:
      - '6379'
    depends_on:
      - redis-primary
    env_file: 
      - ./src/backend/redis-secondary.env

  # Prometheus
  # Prometheus config.yml is configured to point to Grafana Cloud
  prometheus:
    container_name: prometheus
    build: ./src/prometheus
    restart: unless-stopped
    env_file: 
      - ./src/prometheus/prometheus.env
    volumes:
      - ./src/prometheus/config.yml:/etc/prometheus/config.yml
    ports:
      - 9090:9090

  # Promtail is used to send our logs to Grafana cloud
  # Promtail config.yml is configured to point to Grafana Cloud Loki instance
  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.2
    volumes:
      - ./src/promtail/config.yml:/etc/promtail/config.yml
      - log-volume:/home/app/logs
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    env_file:
      - ./src/promtail/promtail.env

  # Grafana for visualization
  # Commented out because we are using Grafana Cloud instead
  #grafana:
  #  container_name: grafana
  #  image: grafana/grafana:5.1.0
  #  volumes:
  #    - ./src/grafana/config.ini:/etc/grafana/grafana.ini
  #    - ./src/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
  #    - ./src/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
  #    - ./src/grafana/dashboards:/var/lib/grafana/dashboards
  #  ports:
  #    - 3000:3000

volumes:
  redis_data:
    driver: local
  traefik-public-certificates:
    driver: local
  log-volume:
  
networks:
  traefik-public:
    external: true