version: '3.9'

services:
  

  # Frontend service
  frontend:
    container_name: frontend
    env_file: 
      - ./src/frontend/frontend.env
    restart: unless-stopped
    build: ./src/frontend
    command: index.js
    volumes:
      - log-volume:/home/app/logs

  # Backend Service
  backend:
    container_name: backend
    env_file: 
      - ./src/backend/backend.env
    restart: unless-stopped
    build: ./src/backend
    ports:
      - "5000:5000"
    volumes:
      - log-volume:/home/app/logs
    command: setup.py -s backend
    depends_on:
      - redis-primary
      - redis-secondary
      - datasync
      - frontend
  
  # Data sync service
  datasync:
    container_name: datasync
    env_file: 
      - ./src/backend/backend.env
    restart: unless-stopped
    build: ./src/backend
    ports:
      - "5001:5001"
    volumes:
      - log-volume:/home/app/logs
    command: setup.py -s sync
    depends_on:
      - redis-primary
      - redis-secondary

  # Public Stats Service
  public:
    container_name: public
    env_file: 
      - ./src/backend/backend.env
    restart: unless-stopped
    build: ./src/backend
    volumes:
      - log-volume:/home/app/logs
    command: setup.py -s public
    ports:
      - "5002:5002"
    depends_on:
      - redis-primary
      - redis-secondary
      - datasync
      - frontend

  # Primary redis
  redis-primary:
    container_name: redis-primary
    image: docker.io/bitnami/redis:6.2
    restart: unless-stopped
    ports:
      - '6379'
    env_file: 
      - ./src/backend/redis-primary.env
    volumes:
      - 'redis_data:/bitnami/redis/data'

  # Secondary Redis
  redis-secondary:
    container_name: redis-secondary
    image: docker.io/bitnami/redis:6.2
    restart: unless-stopped
    ports:
      - '6379'
    depends_on:
      - redis-primary
    env_file: 
      - ./src/backend/redis-secondary.env

  # Prometheus
  # Prometheus config.yml is configured to point to Grafana Cloud
  prometheus:
    container_name: prometheus
    build: ./src/prometheus
    restart: unless-stopped
    env_file: 
      - ./src/prometheus/prometheus.env
    volumes:
      - ./src/prometheus/config.yml:/etc/prometheus/config.yml
    ports:
      - 9090:9090

  # Promtail is used to send our logs to Grafana cloud
  # Promtail config.yml is configured to point to Grafana Cloud Loki instance
  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.2
    volumes:
      - ./src/promtail/config.yml:/etc/promtail/config.yml
      - log-volume:/home/app/logs
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    env_file:
      - ./src/promtail/promtail.env

  # Grafana for visualization
  # Commented out because we are using Grafana Cloud instead
  #grafana:
  #  container_name: grafana
  #  image: grafana/grafana:5.1.0
  #  volumes:
  #    - ./src/grafana/config.ini:/etc/grafana/grafana.ini
  #    - ./src/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
  #    - ./src/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
  #    - ./src/grafana/dashboards:/var/lib/grafana/dashboards
  #  ports:
  #    - 3000:3000

  caddy:
    container_name: caddy
    image: caddy:2.5.2
    restart: unless-stopped
    env_file: 
      - ./src/caddy/caddy.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - public
    environment:
      PROXY_BACKEND: public
      PROXY_PORT: 5002
      DOMAIN: ${DOMAIN}

volumes:
  redis_data:
    driver: local
  caddy_data:
  caddy_config:
  log-volume: