version: '3.9'

services:
  

  # Frontend service
  frontend:
    container_name: frontend
    env_file: 
      - ./src/frontend/frontend.env
    restart: unless-stopped
    build: ./src/frontend
    command: index.js
    volumes:
      - log-volume:/home/app/logs

  # Backend Service
  backend:
    container_name: backend
    env_file: 
      - ./src/backend/backend.env
    restart: unless-stopped
    build: ./src/backend
    ports:
      - "5000:5000"
    volumes:
      - log-volume:/home/app/logs
    command: setup.py -s backend
    depends_on:
      - redis-primary
      - redis-secondary
      - datasync
      - frontend
  
  # Data sync service
  datasync:
    container_name: datasync
    env_file: 
      - ./src/backend/backend.env
    restart: unless-stopped
    build: ./src/backend
    ports:
      - "5001:5001"
    volumes:
      - log-volume:/home/app/logs
    command: setup.py -s sync
    depends_on:
      - redis-primary
      - redis-secondary

  # Public Stats Service
  public:
    container_name: public
    env_file: 
      - ./src/backend/backend.env
    restart: unless-stopped
    build: ./src/backend
    volumes:
      - log-volume:/home/app/logs
    command: setup.py -s public
    ports:
      - "5002:5002"
    depends_on:
      - redis-primary
      - redis-secondary
      - datasync
      - frontend
    labels:
      # Enable Traefik for this specific "backend" service
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=5002
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`api.feyre.io`)
      # Make Traefik use this domain in HTTPS
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.rule=Host(`api.feyre.io`)
      - traefik.http.routers.app-https.tls=true
      # Use the "le" (Let's Encrypt) resolver
      - traefik.http.routers.app-https.tls.certresolver=le
      # https-redirect middleware to redirect HTTP to HTTPS
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # Middleware to redirect HTTP to HTTPS
      - traefik.http.routers.app-http.middlewares=https-redirect
      - traefik.http.routers.app-https.middlewares=admin-auth

  # Primary redis
  redis-primary:
    container_name: redis-primary
    image: docker.io/bitnami/redis:6.2
    restart: unless-stopped
    ports:
      - '6379'
    env_file: 
      - ./src/backend/redis-primary.env
    volumes:
      - 'redis_data:/bitnami/redis/data'

  # Secondary Redis
  redis-secondary:
    container_name: redis-secondary
    image: docker.io/bitnami/redis:6.2
    restart: unless-stopped
    ports:
      - '6379'
    depends_on:
      - redis-primary
    env_file: 
      - ./src/backend/redis-secondary.env

  # Prometheus
  # Prometheus config.yml is configured to point to Grafana Cloud
  prometheus:
    container_name: prometheus
    build: ./src/prometheus
    restart: unless-stopped
    env_file: 
      - ./src/prometheus/prometheus.env
    volumes:
      - ./src/prometheus/config.yml:/etc/prometheus/config.yml
    ports:
      - 9090:9090

  # Promtail is used to send our logs to Grafana cloud
  # Promtail config.yml is configured to point to Grafana Cloud Loki instance
  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.2
    volumes:
      - ./src/promtail/config.yml:/etc/promtail/config.yml
      - log-volume:/home/app/logs
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    env_file:
      - ./src/promtail/promtail.env

  # Grafana for visualization
  # Commented out because we are using Grafana Cloud instead
  #grafana:
  #  container_name: grafana
  #  image: grafana/grafana:5.1.0
  #  volumes:
  #    - ./src/grafana/config.ini:/etc/grafana/grafana.ini
  #    - ./src/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
  #    - ./src/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
  #    - ./src/grafana/dashboards:/var/lib/grafana/dashboards
  #  ports:
  #    - 3000:3000

volumes:
  redis_data:
    driver: local
  traefik-public-certificates:
    driver: local
  log-volume: