version: '3.9'

services:
  # Frontend service
  frontend:
    container_name: frontend
    env_file: 
      - ./src/frontend/.env
    restart: always
    build: ./src/frontend
    command: app.js

  # Backend Service
  backend:
    container_name: backend
    env_file: 
      - ./src/backend/backend.env
    restart: always
    build: ./src/backend
    ports:
      - "5000:5000"
    volumes:
      - ./src/backend/:/home/app/
    command: setup.py -s backend
    depends_on:
      - redis-primary
      - redis-secondary
      - datasync
      - frontend
  
  # Data sync service
  datasync:
    container_name: datasync
    env_file: 
      - ./src/backend/backend.env
    restart: always
    build: ./src/backend
    ports:
      - "5001:5001"
    volumes:
      - ./src/backend/:/home/app/
    command: setup.py -s sync
    depends_on:
      - redis-primary
      - redis-secondary

  # Primary redis
  redis-primary:
    container_name: redis-primary
    image: docker.io/bitnami/redis:6.2
    ports:
      - '6379'
    env_file: 
      - ./src/backend/redis_primary.env
    volumes:
      - 'redis_data:/bitnami/redis/data'

  # Secondary Redis
  redis-secondary:
    container_name: redis-secondary
    image: docker.io/bitnami/redis:6.2
    ports:
      - '6379'
    depends_on:
      - redis-primary
    env_file: 
      - ./src/backend/redis_secondary.env

  # Prometheus server
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.2.1
    volumes:
      - ./src/prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  # Grafana for visualization
  grafana:
    container_name: grafana
    image: grafana/grafana:5.1.0
    volumes:
      - ./src/grafana/config.ini:/etc/grafana/grafana.ini
      - ./src/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./src/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./src/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000

volumes:
  redis_data:
    driver: local
