global:
  scrape_interval:     3s

  external_labels:
      monitor: 'feyre-backend-app'

rule_files:

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5000']
        labels:
          alias: "backend"
  
  - job_name: 'datasync'
    metrics_path: /metrics
    static_configs:
      - targets: ['datasync:5001']
        labels:
          alias: "datasync"