global:
  scrape_interval: 1m

  external_labels:
      monitor: 'feyre'

rule_files:

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: "prometheus"
          env: ${ENV}

  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5000']
        labels:
          instance: "backend"
          env: ${ENV}

  - job_name: 'datasync'
    metrics_path: /metrics
    static_configs:
      - targets: ['datasync:5001']
        labels:
          instance: "datasync"
          env: ${ENV}

remote_write:
- url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
  basic_auth:
    username: ${GRAFANA_USER_ID}
    password: ${GRAFANA_API_KEY}