global:
  scrape_interval:     15s

  external_labels:
      monitor: 'feyre-backend-app'

rule_files:

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:5000']
        labels:
          alias: "backend"

  - job_name: 'datasync'
    metrics_path: /metrics
    static_configs:
      - targets: ['datasync:5001']
        labels:
          alias: "datasync"

remote_write:
- url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
  basic_auth:
    username: ${GRAFNA_USER_ID}
    password: ${GRAFANA_API_KEY}