FROM node:current-alpine3.14

# create nonroot user
RUN adduser nonroot
RUN mkdir /home/app/ && chown -R nonroot:nonroot /home/app
WORKDIR /home/app

COPY --chown=nonroot:nonroot package-lock.json /home/app/
COPY --chown=nonroot:nonroot package.json /home/app/
RUN npm install

USER nonroot

# Feyre.py
COPY --chown=nonroot:nonroot . .

ENTRYPOINT [ "node" ]
