FROM node:stretch-slim

# create nonroot user
RUN adduser nonroot


# Create and own directories
RUN mkdir -p /home/app/
RUN mkdir -p /home/app/logs/
RUN chown -R nonroot:nonroot /home/app

RUN apt update && apt install curl -y

WORKDIR /home/app

COPY --chown=nonroot:nonroot . /home/app/

RUN npm install

USER nonroot

ENTRYPOINT [ "node" ]
CMD [ "index.js" ]
