server:
  http_listen_port: 9080
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
client:
  url: https://168447:${GRAFANA_API_KEY}@logs-prod3.grafana.net/api/prom/push
        
scrape_configs:
- job_name: backend
  static_configs:
  - targets:
      - localhost
    labels:
      app: backend
      job: backend
      env: ${ENV}
      __path__: '/home/app/logs/backend.log'
- job_name: frontend
  static_configs:
  - targets:
      - localhost
    labels:
      app: frontend
      job: frontend
      env: ${ENV}
      __path__: '/home/app/logs/frontend.log'