apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: uptime-kuma
  name: uptime-kuma-pvc
  namespace: uptime-kuma
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
